import json
from pathlib import Path

ACTIVITIES = [
    {
        "name": "ESN Iași — Erasmus Student Network",
        "type": "Club",
        "target": ["Erasmus+", "EU Students", "New Arrivals"],
        "link": "https://www.iasi.esn.ro/",
        "description": "Rețea de voluntari pentru studenți internaționali și Erasmus în Iași: excursii, petreceri, buddy și evenimente de integrare.",
        "keywords": "esn, erasmus, international, volunteering, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Voluntariat ESN Iași",
        "type": "Volunteering",
        "target": ["Erasmus+", "EU Students", "First Year"],
        "link": "https://www.iasi.esn.ro/join-esn-iasi",
        "description": "Înscriere ca voluntar ESN (Evenimente, HR sau PR) pentru a organiza activități pentru studenți de schimb.",
        "keywords": "esn, volunteer, events, international, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "ESN Iași — Evenimente naționale",
        "type": "Event",
        "target": ["Erasmus+", "EU Students"],
        "link": "https://www.iasi.esn.ro/national-events",
        "description": "Excursii și festivaluri la nivel național pentru Erasmus (ex. Halloween in Transylvania, Escape to Vama Veche).",
        "keywords": "esn, trips, festival, erasmus, romania",
        "meeting_location": "Off-campus",
        "schedule": "One-time",
    },
    {
        "name": "AIESEC România — stagii și voluntariat internațional",
        "type": "Club",
        "target": ["First Year", "Graduate", "EU Students", "Non-EU Students"],
        "link": "https://www.aiesec.org.ro/",
        "description": "ONG condus de tineri: stagii globale, proiecte de voluntariat și programe de leadership; birou local sprijină studenții din Iași.",
        "keywords": "aiesec, internship, leadership, international, volunteering",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "Liga AC (LSAC) — viață studențească IT la TUIASI",
        "type": "Club",
        "target": ["First Year", "EU Students"],
        "link": "https://ligaac.ro/",
        "description": "Liga studenților de la Facultatea de Automatică și Calculatoare: ITMarathon, LanParty, workshopuri și evenimente pe campusul Tudor Vladimirescu.",
        "keywords": "lsac, liga ac, programming, tuiasi, it, iasi",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "LSAC Iași — proiecte și recrutare",
        "type": "Event",
        "target": ["First Year", "Graduate"],
        "link": "https://lsaciasi.ro/",
        "description": "Site oficial LSAC: ITMarathon, LanParty, Balul Bobocilor și cum te implici în organizație.",
        "keywords": "lsac, itmarathon, lanparty, tuiasi, students",
        "meeting_location": "On-campus",
        "schedule": "One-time",
    },
    {
        "name": "BEST Iași — Board of European Students of Technology",
        "type": "Club",
        "target": ["First Year", "Graduate", "EU Students"],
        "link": "https://bestis.ro/",
        "description": "ONG studențesc la TUIASI în rețeaua BEST europeană: competiții inginerești, summer courses, JobShop și techathonul PROVE IT.",
        "keywords": "best, engineering, tuiasi, competition, technology",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "BEST Iași — PROVE IT & symposium",
        "type": "Event",
        "target": ["Graduate", "EU Students"],
        "link": "https://bestis.ro/despre-noi/",
        "description": "Evenimente anuale BEST Iași: PROVE IT (techathon 24h), BEST Symposium și cursuri de vară BEST în Europa.",
        "keywords": "best, techathon, prove it, hackathon, tuiasi",
        "meeting_location": "On-campus",
        "schedule": "One-time",
    },
    {
        "name": "IEEE Student Branch — TUIASI",
        "type": "Club",
        "target": ["Graduate", "PhD", "EU Students"],
        "link": "https://edu.ieee.org/ro-gaitu/",
        "description": "Filiala IEEE la Universitatea Tehnică Gheorghe Asachi: prezentări tehnice, workshopuri și networking pentru studenți ETTI.",
        "keywords": "ieee, electronics, engineering, tuiasi, workshops",
        "meeting_location": "On-campus",
        "schedule": "Biweekly",
    },
    {
        "name": "TUIASI — Organizații studențești (campus Tudor Vladimirescu)",
        "type": "Club",
        "target": ["First Year", "New Arrivals", "Non-EU Students"],
        "link": "https://campus.tuiasi.ro/en/student-organisations/",
        "description": "Lista oficială a ONG-urilor studențești pe campus: BEST, LSAC, ASII și ligi de facultate.",
        "keywords": "tuiasi, campus, student organisations, ngo, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Zilele Campusului Tudor Vladimirescu (TUIASI)",
        "type": "Event",
        "target": ["First Year", "EU Students", "Erasmus+"],
        "link": "https://campus.tuiasi.ro/",
        "description": "Festival studențesc de câteva zile pe campus: concerte, sport, târg de joburi și petreceri — printre cele mai mari evenimente universitare din România.",
        "keywords": "tuiasi, festival, campus, concert, student life",
        "meeting_location": "On-campus",
        "schedule": "One-time",
    },
    {
        "name": "Liga Studenților Economiști (LSE Iași)",
        "type": "Club",
        "target": ["First Year", "EU Students"],
        "link": "https://lse.ro/",
        "description": "ONG al studenților FEAA de la UAIC: proiecte profesionale, săptămâna bobocilor, Zilele Studentului Economist și voluntariat.",
        "keywords": "lse, economics, feaa, uaic, business, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "LSE Iași — proiecte și evenimente",
        "type": "Event",
        "target": ["First Year", "Graduate"],
        "link": "https://lse.ro/proiecte/",
        "description": "Calendar LSE: Zilele Studentului Economist, Iași Street Games, Balul Bobocilor și participare la FestudIS.",
        "keywords": "lse, festival, sports, feaa, uaic",
        "meeting_location": "Hybrid",
        "schedule": "One-time",
    },
    {
        "name": "FEAA UAIC — Organizații studențești",
        "type": "Club",
        "target": ["EU Students", "Erasmus+"],
        "link": "https://www.feaa.uaic.ro/students/student-organizations/?lang=en",
        "description": "Pagină oficială FEAA cu LSE, CEAI și alte ONG-uri economice — contacte și misiuni.",
        "keywords": "feaa, uaic, student organizations, economics, iasi",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "UAIC — Asociații studențești (ghid Erasmus)",
        "type": "Club",
        "target": ["Erasmus+", "New Arrivals"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/student-associations/",
        "description": "Prezentare a asociațiilor studențești de la Universitatea Alexandru Ioan Cuza pentru studenți internaționali.",
        "keywords": "uaic, associations, erasmus, clubs, iasi",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "UAIC — Activități extrașcolare",
        "type": "Cultural",
        "target": ["Erasmus+", "EU Students", "First Year"],
        "link": "https://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/extra-mural-activities/",
        "description": "Ghid universitar la cluburi, activități culturale și viață studențească în afara cursurilor.",
        "keywords": "uaic, extracurricular, culture, student life",
        "meeting_location": "Hybrid",
        "schedule": "Weekly",
    },
    {
        "name": "UAIC — Facilități sport și timp liber",
        "type": "Sport",
        "target": ["EU Students", "Non-EU Students", "First Year"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/sports-leisure-facilities/",
        "description": "Săli de sport și opțiuni de recreere pentru studenții UAIC în Iași.",
        "keywords": "uaic, sports, gym, fitness, leisure",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Erasmus Day la UAIC",
        "type": "Event",
        "target": ["Erasmus+", "EU Students"],
        "link": "https://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/erasmus-day/",
        "description": "Sărbătoare anuală Erasmus+ la UAIC: standuri informaționale, workshopuri și networking.",
        "keywords": "erasmus day, uaic, mobility, international",
        "meeting_location": "On-campus",
        "schedule": "One-time",
    },
    {
        "name": "IEEE Student Branch — UAIC (Fizică)",
        "type": "Club",
        "target": ["Graduate", "PhD"],
        "link": "https://stoner.phys.uaic.ro/ieee/ieee-student-branch-iasi.html",
        "description": "Filială IEEE la Facultatea de Fizică UAIC: seminarii pentru studenți interesați de inginerie și științe aplicate.",
        "keywords": "ieee, uaic, physics, engineering, seminars",
        "meeting_location": "On-campus",
        "schedule": "Biweekly",
    },
    {
        "name": "Casa de Cultură a Studenților Iași (CCS)",
        "type": "Cultural",
        "target": ["First Year", "EU Students", "Erasmus+"],
        "link": "https://www.ccsiasi.ro/",
        "description": "Casa de cultură studențească din 1957: cursuri de artă, training leadership, festivaluri pe Bd. Carol I.",
        "keywords": "ccs, culture, arts, student house, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "FEStudIS — Festivalul Studenților Ieșeni",
        "type": "Event",
        "target": ["First Year", "EU Students", "Erasmus+"],
        "link": "https://www.ccsiasi.ro/evenimente-2/festudis-2023",
        "description": "Cel mai mare festival studențesc din Iași (început de mai): paradă ONG-uri, concerte, teatru, workshopuri și sport.",
        "keywords": "festudis, festival, parade, students, iasi",
        "meeting_location": "Off-campus",
        "schedule": "One-time",
    },
    {
        "name": "Habitat for Humanity — Hope Build (voluntariat construcții)",
        "type": "Volunteering",
        "target": ["EU Students", "Graduate", "First Year"],
        "link": "https://www.habitat.ro/hopebuild-fiivoluntar/",
        "description": "Construcție accelerată de locuințe; echipe de studenți din zona Iași (ex. Țuțora) pot participa 1–5 zile.",
        "keywords": "habitat, volunteering, construction, community, iasi",
        "meeting_location": "Off-campus",
        "schedule": "One-time",
    },
    {
        "name": "Palatul Culturii Iași — muzee",
        "type": "Cultural",
        "target": ["Erasmus+", "New Arrivals", "EU Students"],
        "link": "https://palatulculturii.ro/",
        "description": "Complex cultural emblematic: muzee de istorie, artă și știință, foarte vizitat de studenți internaționali.",
        "keywords": "museum, culture, history, tourism, iasi",
        "meeting_location": "Off-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Teatrul Național „Vasile Alecsandri” Iași",
        "type": "Cultural",
        "target": ["EU Students", "Erasmus+"],
        "link": "https://www.teatrulnationaliasi.ro/",
        "description": "Teatru național cu spectacole în română și internaționale; bilete reduse pentru studenți.",
        "keywords": "theatre, culture, performances, iasi",
        "meeting_location": "Off-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Muzeul Unirii Iași",
        "type": "Cultural",
        "target": ["New Arrivals", "Erasmus+"],
        "link": "https://www.muzeulunirii.ro/",
        "description": "Muzeul Unirii în Palatul Culturii — istorie românească; vizite frecvente în grupuri studențești.",
        "keywords": "museum, history, union, culture, iasi",
        "meeting_location": "Off-campus",
        "schedule": "Monthly",
    },
    {
        "name": "UAIC — Evenimente locale principale în Iași",
        "type": "Event",
        "target": ["Erasmus+", "New Arrivals"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/main-local-events/",
        "description": "Ghid UAIC la festivaluri, concerte și evenimente culturale din oraș pentru studenți internaționali.",
        "keywords": "events, festival, city, culture, uaic",
        "meeting_location": "Off-campus",
        "schedule": "Monthly",
    },
    {
        "name": "Cunoaște orașul Iași (ghid UAIC)",
        "type": "Cultural",
        "target": ["New Arrivals", "Non-EU Students", "Erasmus+"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/meet-city-iasi/",
        "description": "Sfaturi oficiale de orientare: cartiere, transport și obiective de vizitat pentru studenți de schimb.",
        "keywords": "city guide, tourism, iasi, erasmus, orientation",
        "meeting_location": "Off-campus",
        "schedule": "One-time",
    },
    {
        "name": "Viața în Iași — ghid TUIASI internațional",
        "type": "Cultural",
        "target": ["Non-EU Students", "New Arrivals"],
        "link": "https://study.tuiasi.ro/living-in-iasi/",
        "description": "Ghid practic pentru studenți internaționali TUIASI: cazare, costuri, mâncare și timp liber în Iași.",
        "keywords": "living, iasi, international, tuiasi, student life",
        "meeting_location": "Off-campus",
        "schedule": "One-time",
    },
    {
        "name": "Parcul Copou — ieșiri în aer liber lângă UAIC",
        "type": "Sport",
        "target": ["EU Students", "First Year", "Erasmus+"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/meet-city-iasi/#copou",
        "description": "Zonă verde lângă campusul Copou UAIC: alergare, picnicuri și întâlniri informale între studenți.",
        "keywords": "copou, park, outdoors, running, social",
        "meeting_location": "Off-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Centrul medical studențesc Copou (UAIC)",
        "type": "Event",
        "target": ["EU Students", "Non-EU Students"],
        "link": "https://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/copou-student-medical-center/",
        "description": "Servicii medicale pe campus pentru studenții UAIC: program și înscriere pentru consultații.",
        "keywords": "health, medical, uaic, student services",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Biblioteci UAIC — spații de studiu",
        "type": "Study Group",
        "target": ["Graduate", "PhD", "First Year"],
        "link": "http://www.uaic.ro/en/international/erasmus-programme/erasmus-incoming-students/libraries-iasi/",
        "description": "Rețea de biblioteci universitare în Iași cu săli de lectură și resurse digitale pentru studiu individual sau în grup.",
        "keywords": "library, study, research, uaic, quiet",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "TUIASI — Campus și cazare (internațional)",
        "type": "Cultural",
        "target": ["Non-EU Students", "New Arrivals"],
        "link": "https://study.tuiasi.ro/campus-and-living/",
        "description": "Facilități campus, cămine și resurse de viață studențească pentru internaționali la TUIASI.",
        "keywords": "tuiasi, campus, dorms, facilities, international",
        "meeting_location": "On-campus",
        "schedule": "One-time",
    },
    {
        "name": "TUIASI — Programe de schimb și Erasmus",
        "type": "Event",
        "target": ["Erasmus+", "EU Students"],
        "link": "https://study.tuiasi.ro/exchange-programs/",
        "description": "Informații mobilitate, universități partenere și planificarea unui semestru în străinătate de la TUIASI.",
        "keywords": "erasmus, exchange, mobility, tuiasi, international",
        "meeting_location": "Hybrid",
        "schedule": "One-time",
    },
    {
        "name": "CCS Iași — Cursuri de artă",
        "type": "Cultural",
        "target": ["First Year", "EU Students"],
        "link": "https://www.ccsiasi.ro/despre-noi",
        "description": "Ateliere creative la Casa de Cultură: pictură, dans, fotografie și chitară pentru studenți.",
        "keywords": "arts, dance, painting, workshops, ccs",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Descoperă TUIASI — BEST",
        "type": "Club",
        "target": ["First Year"],
        "link": "https://descopera.tuiasi.ro/best/",
        "description": "Articol portal universitar despre BEST Iași și cum te implici în activități inginerești.",
        "keywords": "tuiasi, best, student organisations",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "Descoperă TUIASI — LSAC",
        "type": "Club",
        "target": ["First Year"],
        "link": "https://descopera.tuiasi.ro/lsac/",
        "description": "Prezentare LSAC și ligi studențești la Facultatea de Automatică și Calculatoare.",
        "keywords": "lsac, tuiasi, student organisations, faculty",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "Grădina Botanică Anastasie Fătu (UAIC)",
        "type": "Cultural",
        "target": ["EU Students", "Erasmus+", "First Year"],
        "link": "https://www.uaic.ro/en/gradina-botanica-anastasie-fatu/",
        "description": "Grădina botanică UAIC — plimbări, evenimente educative și relaxare în natură pentru studenți.",
        "keywords": "botanical garden, nature, uaic, outdoor, iasi",
        "meeting_location": "Off-campus",
        "schedule": "Weekly",
    },
    {
        "name": "Planetariu UAIC",
        "type": "Cultural",
        "target": ["First Year", "EU Students"],
        "link": "https://www.uaic.ro/en/planetarium/",
        "description": "Sesiuni și evenimente de astronomie la planetariul universității — potrivit pentru ieșiri de grup.",
        "keywords": "planetarium, astronomy, science, uaic, iasi",
        "meeting_location": "On-campus",
        "schedule": "Monthly",
    },
    {
        "name": "Evenimente UNAGE — George Enescu",
        "type": "Cultural",
        "target": ["EU Students", "Erasmus+"],
        "link": "https://www.arteiasi.ro/en/category/events/",
        "description": "Concerte, spectacole și expoziții la Universitatea Națională de Arte George Enescu din Iași.",
        "keywords": "unage, arts, concerts, events, iasi",
        "meeting_location": "On-campus",
        "schedule": "Weekly",
    },
]

path = Path(__file__).resolve().parent / "verified_links.json"
data = json.loads(path.read_text(encoding="utf-8"))
data["activities"] = ACTIVITIES
path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(len(ACTIVITIES))
